sudo: required
services:
  - docker

before_install:
  - docker build -t asm94/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run asm94/docker-react npm test -- --coverage

after_success:
  - docker build -t asm494/multi-client ./client
  - docker build -t asm494/multi-nginx ./nginx
  - docker build -t asm494/multi-server ./server
  - docker build -t asm494/multi-worker ./worker
  # Login Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Images to Docker Hub
  - docker push asm494/multi-client
  - docker push asm494/multi-nginx
  - docker push asm494/multi-server
  - docker push asm494/multi-worker